export const locations = [
  {
    name: "Junipero Serra Park",
    address: "1801 Crystal Springs Rd, San Bruno, CA 94066",
    lat: 37.6389,
    lon: -122.4169,
    spotScore: 91,
    scent: 0.95,
    smellLabel: "pine, dry grass, woodsy",
    parkingLabel: "Easy",
    vibeLabel: "Quiet, natural, panoramic",
    bestFor: "woodsy smell, elevation, panoramic west views",
    whyItWins: "Perfect combo of elevation, trees, clean air, and open horizon.",
  },
  {
    name: "Bayfront Park",
    address: "1600 Bayshore Hwy, Burlingame, CA 94010",
    lat: 37.5898,
    lon: -122.3639,
    spotScore: 84,
    scent: 0.75,
    smellLabel: "clean, slight water, generally mild",
    parkingLabel: "Easy",
    vibeLabel: "Open, airy, reflective",
    bestFor: "open sky, reflections, easy access",
    whyItWins: "Less woodsy, but a very open sky makes color spread wider.",
  },
  {
    name: "Skyline College Hills",
    address: "3300 College Dr, San Bruno, CA 94066",
    lat: 37.6305,
    lon: -122.4682,
    spotScore: 88,
    scent: 0.9,
    smellLabel: "dry grass, hillside, fresh air",
    parkingLabel: "Easy",
    vibeLabel: "Elevated, expansive, quiet",
    bestFor: "elevation, hillside air, stronger sky intensity",
    whyItWins: "Elevation amplifies sunset intensity and gives a bigger sky feel.",
  },
]
