import { TrustStrip } from "@/components/TrustStrip";
import { MarketingGraphicsStack } from "@/components/MarketingGraphicsStack";
import { ProcessFlowSection } from "@/components/ProcessFlowSection";
import { HeroProductPanel } from "@/components/HeroProductPanel";
import ClientSafeBoundary from "@/components/ClientSafeBoundary"
import EducationRotator from "@/components/EducationRotator"
import GlobalSunsetBoard from "@/components/GlobalSunsetBoard"
import PerfectSunsetFramework from "@/components/PerfectSunsetFramework"
import LiveSunsetDashboard from "@/components/LiveSunsetDashboard"

export const dynamic = "force-dynamic"
export const revalidate = 0

export default function Home() {
  return (
    <main className="min-h-screen bg-black text-white">
        <div className="mx-auto max-w-6xl px-4 py-4 sm:px-6">
          <TrustStrip />
        </div>

      <div className="fixed inset-0 -z-10 overflow-hidden">
        <div className="absolute left-[-10%] top-[-10%] h-[420px] w-[420px] rounded-full bg-fuchsia-500/20 blur-3xl" />
        <div className="absolute right-[-8%] top-[8%] h-[360px] w-[360px] rounded-full bg-sky-500/20 blur-3xl" />
        <div className="absolute bottom-[-10%] left-[20%] h-[420px] w-[420px] rounded-full bg-orange-500/15 blur-3xl" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.08),transparent_35%),linear-gradient(180deg,#050505_0%,#0a0a0f_45%,#060606_100%)]" />
      </div>

      <div className="mx-auto max-w-7xl px-4 py-6 md:px-6 md:py-8">
        <section className="mb-8 grid gap-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-end">
          <div>
            <div className="mb-5 inline-flex rounded-full border border-white/10 bg-white/10 px-4 py-2 text-[11px] font-medium uppercase tracking-[0.28em] text-zinc-300 backdrop-blur-xl">
              SUNSETX · Live Sunset Intelligence
            </div>
            <h1 className="max-w-3xl text-4xl font-semibold tracking-tight text-white sm:text-5xl md:text-6xl">
              Find the sunset worth going outside for.
            </h1>
            <p className="mt-4 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">
              Weather, timing, and location scored into a live board—so you can pick a sky, not guess from a weather app.
            </p>
            <div className="mt-6 flex flex-wrap gap-3">
              <a href="#live" className="rounded-full bg-orange-400 px-5 py-2.5 text-sm font-semibold text-zinc-950">
                Open live board
              </a>
              <a href="#framework" className="rounded-full border border-white/15 px-5 py-2.5 text-sm text-white">
                How scoring works
              </a>
            </div>
          </div>
          <p className="text-xs leading-6 text-zinc-500">
            Rankings and glow scores are generated by the SunsetX model from public weather and timing inputs. They are planning signals, not guaranteed sky conditions.
          </p>
        </section>

        <div className="space-y-5">
          <div id="live" className="scroll-mt-20">
            <ClientSafeBoundary fallbackTitle="Live sunset dashboard">
              <LiveSunsetDashboard />
            </ClientSafeBoundary>
          </div>

          <div id="education" className="scroll-mt-20">
            <ClientSafeBoundary fallbackTitle="Sunset education">
              <EducationRotator />
            </ClientSafeBoundary>
          </div>

          <div id="board" className="scroll-mt-20">
            <ClientSafeBoundary fallbackTitle="Global sunset board">
              <GlobalSunsetBoard />
            </ClientSafeBoundary>
          </div>

          <div id="framework" className="scroll-mt-20">
            <ClientSafeBoundary fallbackTitle="Perfect sunset framework">
              <PerfectSunsetFramework />
            </ClientSafeBoundary>
          </div>
        </div>
      </div>
      <section className="mx-auto max-w-6xl px-4 pb-16 pt-8 sm:px-6"><HeroProductPanel /></section>
      <ProcessFlowSection />
    <MarketingGraphicsStack />
    </main>
  )
}
